-- MVP schema for Player/Game/Team/Result services
-- MySQL 8+

CREATE TABLE players (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  shirt_number INT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  deleted_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_players_nickname (nickname),
  UNIQUE KEY uq_players_shirt_number (shirt_number),
  CHECK (rating BETWEEN 0 AND 100),
  CHECK (shirt_number > 0)
) ENGINE=InnoDB;

CREATE TABLE games (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  starts_at DATETIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  status ENUM('DRAFT','CONFIRMING','CONFIRMED','FINISHED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE game_participants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT UNSIGNED NOT NULL,
  player_id BIGINT UNSIGNED NOT NULL,
  invite_status ENUM('INVITED','CONFIRMED','DECLINED') NOT NULL DEFAULT 'INVITED',
  confirmed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_game_player (game_id, player_id),
  CONSTRAINT fk_gp_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_gp_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE team_sets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT UNSIGNED NOT NULL,
  mode ENUM('AUTO','MANUAL') NOT NULL,
  status ENUM('DRAFT','LOCKED') NOT NULL DEFAULT 'DRAFT',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teamset_game_version (game_id, version),
  CONSTRAINT fk_teamset_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE teams (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  team_set_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  order_index INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teamset_order (team_set_id, order_index),
  CONSTRAINT fk_team_teamset FOREIGN KEY (team_set_id) REFERENCES team_sets(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE team_players (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT UNSIGNED NOT NULL,
  player_id BIGINT UNSIGNED NOT NULL,
  position VARCHAR(50) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_team_player (team_id, player_id),
  CONSTRAINT fk_tp_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_tp_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE game_results (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT UNSIGNED NOT NULL,
  format ENUM('TWO_TEAMS','THREE_TEAMS') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_result_game (game_id),
  CONSTRAINT fk_result_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE result_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_result_id BIGINT UNSIGNED NOT NULL,
  team_a_id BIGINT UNSIGNED NOT NULL,
  team_b_id BIGINT UNSIGNED NOT NULL,
  score_a INT UNSIGNED NOT NULL,
  score_b INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_rl_result FOREIGN KEY (game_result_id) REFERENCES game_results(id) ON DELETE CASCADE,
  CONSTRAINT fk_rl_team_a FOREIGN KEY (team_a_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_rl_team_b FOREIGN KEY (team_b_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CHECK (score_a >= 0),
  CHECK (score_b >= 0),
  CHECK (team_a_id <> team_b_id),
  UNIQUE KEY uq_result_line_pair (game_result_id, team_a_id, team_b_id)
) ENGINE=InnoDB;
